# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "rack", ">=1.5"
gem "faye-websocket", ">=0.10"
gem "puma", ">=2.0"
